name: trng
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.4.0
  provider: ^6.0.0
  sqflite:
  path:
  firebase_auth:
  flutter_dotenv:
  cupertino_icons: ^1.0.6
  firebase_core:
  cloud_firestore:
  syncfusion_flutter_charts: ^26.2.7  # or the latest version available
  bluetooth_low_energy: ^6.0.2
  flutter_blue_plus: ^1.32.12
  permission_handler: ^10.0.0
  logger: ^2.4.0
  connectivity_plus: ^2.3.0
  shared_preferences: ^2.1.0
  wakelock:


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite:
  sqflite_common_ffi:


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env